ZENKO-4564: higher resilience with apt locks for deps installation

diff --git a/.github/actions/install-end2end-dependencies/action.yaml b/.github/actions/install-end2end-dependencies/action.yaml
--- a/.github/actions/install-end2end-dependencies/action.yaml
+++ b/.github/actions/install-end2end-dependencies/action.yaml
@@ -8,9 +8,33 @@ runs:
     - name: Install dependencies
       shell: bash
       run: |-
+          function retry() {
+            local retries=$1
+            local delay=$2
+            shift 2
+
+            local count=1
+            while [ $count -le "$retries" ]; do
+              if ( "$@" ); then
+                return 0
+              fi
+
+              echo "Attempt $count/$retries failed. Retrying in $delay seconds..."
+              sleep "$delay"
+              count=$(( count + 1 ))
+            done
+
+            echo "All attempts failed. Exiting..."
+            exit 1
+          }
+
+          function retry_apt_get() {
+            retry 5 5 sudo apt-get "$@"
+          }
+
           set -exu;
-          sudo apt-get update
-          sudo apt-get install -y \
+          retry_apt_get update
+          retry_apt_get install -y \
             apt-transport-https \
             ca-certificates \
             curl \
@@ -27,8 +51,8 @@ runs:
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
-          sudo apt-get update
-          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+          retry_apt_get update
+          retry_apt_get install -y docker-ce docker-ce-cli containerd.io
           sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
           sudo echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
           sudo curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${{ env.KIND_VERSION }}/kind-linux-amd64
